#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall $(shell sdl2-config --cflags)
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = $(shell sdl2-config --libs)

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g -DDEBUG
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/QuattroPlay

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2 -DRELEASE
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/QuattroPlay

OBJ_DEBUG = $(OBJDIR_DEBUG)/drv/voice_env.o $(OBJDIR_DEBUG)/drv/voice_lfo.o $(OBJDIR_DEBUG)/drv/voice_pan.o $(OBJDIR_DEBUG)/drv/voice_pitch.o $(OBJDIR_DEBUG)/drv/wave.o $(OBJDIR_DEBUG)/fileio.o $(OBJDIR_DEBUG)/ini.o $(OBJDIR_DEBUG)/loader.o $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/ui.o $(OBJDIR_DEBUG)/ui_infobar.o $(OBJDIR_DEBUG)/ui_menu.o $(OBJDIR_DEBUG)/ui_pattern.o $(OBJDIR_DEBUG)/vgm.o $(OBJDIR_DEBUG)/audio.o $(OBJDIR_DEBUG)/c352.o $(OBJDIR_DEBUG)/drv/helper.o $(OBJDIR_DEBUG)/drv/quattro.o $(OBJDIR_DEBUG)/drv/tables.o $(OBJDIR_DEBUG)/drv/track.o $(OBJDIR_DEBUG)/drv/track_cmd.o $(OBJDIR_DEBUG)/drv/update.o $(OBJDIR_DEBUG)/drv/voice.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/drv/voice_env.o $(OBJDIR_RELEASE)/drv/voice_lfo.o $(OBJDIR_RELEASE)/drv/voice_pan.o $(OBJDIR_RELEASE)/drv/voice_pitch.o $(OBJDIR_RELEASE)/drv/wave.o $(OBJDIR_RELEASE)/fileio.o $(OBJDIR_RELEASE)/ini.o $(OBJDIR_RELEASE)/loader.o $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/ui.o $(OBJDIR_RELEASE)/ui_infobar.o $(OBJDIR_RELEASE)/ui_pattern.o $(OBJDIR_RELEASE)/ui_menu.o $(OBJDIR_RELEASE)/vgm.o $(OBJDIR_RELEASE)/audio.o $(OBJDIR_RELEASE)/c352.o $(OBJDIR_RELEASE)/drv/helper.o $(OBJDIR_RELEASE)/drv/quattro.o $(OBJDIR_RELEASE)/drv/tables.o $(OBJDIR_RELEASE)/drv/track.o $(OBJDIR_RELEASE)/drv/track_cmd.o $(OBJDIR_RELEASE)/drv/update.o $(OBJDIR_RELEASE)/drv/voice.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/drv || mkdir -p $(OBJDIR_DEBUG)/drv
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/drv/voice_env.o: drv/voice_env.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c drv/voice_env.c -o $(OBJDIR_DEBUG)/drv/voice_env.o

$(OBJDIR_DEBUG)/drv/voice_lfo.o: drv/voice_lfo.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c drv/voice_lfo.c -o $(OBJDIR_DEBUG)/drv/voice_lfo.o

$(OBJDIR_DEBUG)/drv/voice_pan.o: drv/voice_pan.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c drv/voice_pan.c -o $(OBJDIR_DEBUG)/drv/voice_pan.o

$(OBJDIR_DEBUG)/drv/voice_pitch.o: drv/voice_pitch.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c drv/voice_pitch.c -o $(OBJDIR_DEBUG)/drv/voice_pitch.o

$(OBJDIR_DEBUG)/drv/wave.o: drv/wave.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c drv/wave.c -o $(OBJDIR_DEBUG)/drv/wave.o

$(OBJDIR_DEBUG)/fileio.o: fileio.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c fileio.c -o $(OBJDIR_DEBUG)/fileio.o

$(OBJDIR_DEBUG)/ini.o: ini.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ini.c -o $(OBJDIR_DEBUG)/ini.o

$(OBJDIR_DEBUG)/loader.o: loader.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c loader.c -o $(OBJDIR_DEBUG)/loader.o

$(OBJDIR_DEBUG)/main.o: main.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.c -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/ui.o: ui.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ui.c -o $(OBJDIR_DEBUG)/ui.o

$(OBJDIR_DEBUG)/ui_infobar.o: ui_infobar.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ui_infobar.c -o $(OBJDIR_DEBUG)/ui_infobar.o
	
$(OBJDIR_DEBUG)/ui_pattern.o: ui_pattern.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ui_pattern.c -o $(OBJDIR_DEBUG)/ui_pattern.o

$(OBJDIR_DEBUG)/ui_menu.o: ui_menu.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ui_menu.c -o $(OBJDIR_DEBUG)/ui_menu.o

$(OBJDIR_DEBUG)/vgm.o: vgm.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c vgm.c -o $(OBJDIR_DEBUG)/vgm.o

$(OBJDIR_DEBUG)/audio.o: audio.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c audio.c -o $(OBJDIR_DEBUG)/audio.o

$(OBJDIR_DEBUG)/c352.o: c352.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c c352.c -o $(OBJDIR_DEBUG)/c352.o

$(OBJDIR_DEBUG)/drv/helper.o: drv/helper.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c drv/helper.c -o $(OBJDIR_DEBUG)/drv/helper.o

$(OBJDIR_DEBUG)/drv/quattro.o: drv/quattro.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c drv/quattro.c -o $(OBJDIR_DEBUG)/drv/quattro.o

$(OBJDIR_DEBUG)/drv/tables.o: drv/tables.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c drv/tables.c -o $(OBJDIR_DEBUG)/drv/tables.o

$(OBJDIR_DEBUG)/drv/track.o: drv/track.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c drv/track.c -o $(OBJDIR_DEBUG)/drv/track.o

$(OBJDIR_DEBUG)/drv/track_cmd.o: drv/track_cmd.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c drv/track_cmd.c -o $(OBJDIR_DEBUG)/drv/track_cmd.o

$(OBJDIR_DEBUG)/drv/update.o: drv/update.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c drv/update.c -o $(OBJDIR_DEBUG)/drv/update.o

$(OBJDIR_DEBUG)/drv/voice.o: drv/voice.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c drv/voice.c -o $(OBJDIR_DEBUG)/drv/voice.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/drv
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/drv || mkdir -p $(OBJDIR_RELEASE)/drv
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/drv/voice_env.o: drv/voice_env.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c drv/voice_env.c -o $(OBJDIR_RELEASE)/drv/voice_env.o

$(OBJDIR_RELEASE)/drv/voice_lfo.o: drv/voice_lfo.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c drv/voice_lfo.c -o $(OBJDIR_RELEASE)/drv/voice_lfo.o

$(OBJDIR_RELEASE)/drv/voice_pan.o: drv/voice_pan.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c drv/voice_pan.c -o $(OBJDIR_RELEASE)/drv/voice_pan.o

$(OBJDIR_RELEASE)/drv/voice_pitch.o: drv/voice_pitch.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c drv/voice_pitch.c -o $(OBJDIR_RELEASE)/drv/voice_pitch.o

$(OBJDIR_RELEASE)/drv/wave.o: drv/wave.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c drv/wave.c -o $(OBJDIR_RELEASE)/drv/wave.o

$(OBJDIR_RELEASE)/fileio.o: fileio.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c fileio.c -o $(OBJDIR_RELEASE)/fileio.o

$(OBJDIR_RELEASE)/ini.o: ini.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ini.c -o $(OBJDIR_RELEASE)/ini.o

$(OBJDIR_RELEASE)/loader.o: loader.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c loader.c -o $(OBJDIR_RELEASE)/loader.o

$(OBJDIR_RELEASE)/main.o: main.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.c -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/ui.o: ui.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ui.c -o $(OBJDIR_RELEASE)/ui.o

$(OBJDIR_RELEASE)/ui_infobar.o: ui_infobar.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ui_infobar.c -o $(OBJDIR_RELEASE)/ui_infobar.o

$(OBJDIR_RELEASE)/ui_menu.o: ui_menu.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ui_menu.c -o $(OBJDIR_RELEASE)/ui_menu.o

$(OBJDIR_RELEASE)/ui_pattern.o: ui_pattern.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ui_pattern.c -o $(OBJDIR_RELEASE)/ui_pattern.o

$(OBJDIR_RELEASE)/vgm.o: vgm.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c vgm.c -o $(OBJDIR_RELEASE)/vgm.o

$(OBJDIR_RELEASE)/audio.o: audio.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c audio.c -o $(OBJDIR_RELEASE)/audio.o

$(OBJDIR_RELEASE)/c352.o: c352.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c c352.c -o $(OBJDIR_RELEASE)/c352.o

$(OBJDIR_RELEASE)/drv/helper.o: drv/helper.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c drv/helper.c -o $(OBJDIR_RELEASE)/drv/helper.o

$(OBJDIR_RELEASE)/drv/quattro.o: drv/quattro.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c drv/quattro.c -o $(OBJDIR_RELEASE)/drv/quattro.o

$(OBJDIR_RELEASE)/drv/tables.o: drv/tables.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c drv/tables.c -o $(OBJDIR_RELEASE)/drv/tables.o

$(OBJDIR_RELEASE)/drv/track.o: drv/track.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c drv/track.c -o $(OBJDIR_RELEASE)/drv/track.o

$(OBJDIR_RELEASE)/drv/track_cmd.o: drv/track_cmd.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c drv/track_cmd.c -o $(OBJDIR_RELEASE)/drv/track_cmd.o

$(OBJDIR_RELEASE)/drv/update.o: drv/update.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c drv/update.c -o $(OBJDIR_RELEASE)/drv/update.o

$(OBJDIR_RELEASE)/drv/voice.o: drv/voice.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c drv/voice.c -o $(OBJDIR_RELEASE)/drv/voice.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/drv
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

